### ISSUE TITLE
Messari' object has no attribute 'url'

### ISSUE THREAD

**Issue by itzmestar** [itzmestar/Messari#1]
m = Messari('3d5ee5b0-09de-4be1-ae64-0e33367a36cb')
r = m.get_asset_metrics('btc')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\py_game\venv38\lib\site-packages\messari-0.2.0-py3.8.egg\messari\messari.py", line 91, in get_asset_metrics
    return self._get(path)
  File "D:\py_game\venv38\lib\site-packages\messari-0.2.0-py3.8.egg\messari\messari.py", line 48, in _get
    return self._send_message('GET', endpoint, params=params)
  File "D:\py_game\venv38\lib\site-packages\messari-0.2.0-py3.8.egg\messari\messari.py", line 36, in _send_message
    url = self.url + endpoint
AttributeError: 'Messari' object has no attribute 'url'

**Comment by itzmestar** [comment]
solved in current commit v0.2.1

**Comment by itzmestar** [comment]
solved in current commit v0.2.1
